export const userInfo = [
    {
        firstName: "Amit",
        lastName: "Shaw",
        phone: "8789906286",
        email: "iamitshaw.101@gmail.com",
        job: "Software Engineer",
        gender: "male",
        countryCode: "+91 - ",
    },
    {
        firstName: "John",
        lastName: "Doe",
        phone: "5551234567",
        email: "johndoe@example.com",
        job: "Web Developer",
        gender: "male",
        countryCode: "+1 - ",
    },
    {
        firstName: "Jane",
        lastName: "Smith",
        phone: "2079460958",
        email: "janesmith@example.com",
        job: "Product Manager",
        gender: "female",
        countryCode: "+44 - ",
    },
    {
        firstName: "Alice",
        lastName: "Johnson",
        phone: "293744000",
        email: "alicejohnson@example.com",
        job: "UX Designer",
        gender: "female",
        countryCode: "+61 - ",
    },
    {
        firstName: "Bob",
        lastName: "Brown",
        phone: "911234567",
        email: "bobbrown@example.com",
        job: "Data Scientist",
        gender: "male",
        countryCode: "+34 - ",
    },
    {
        firstName: "Charlie",
        lastName: "Davis",
        phone: "30123456",
        email: "charliedavis@example.com",
        job: "DevOps Engineer",
        gender: "male",
        countryCode: "+49 - ",
    },
    {
        firstName: "Diana",
        lastName: "Evans",
        phone: "123456789",
        email: "dianaevans@example.com",
        job: "HR Manager",
        gender: "female",
        countryCode: "+33 - ",
    },
    {
        firstName: "Edward",
        lastName: "Garcia",
        phone: "1012345678",
        email: "edwardgarcia@example.com",
        job: "Finance Analyst",
        gender: "male",
        countryCode: "+86 - ",
    },
    {
        firstName: "Fiona",
        lastName: "Harris",
        phone: "312345678",
        email: "fionaharris@example.com",
        job: "Marketing Specialist",
        gender: "female",
        countryCode: "+81 - ",
    },
    {
        firstName: "George",
        lastName: "Ingram",
        phone: "4951234567",
        email: "georgeingram@example.com",
        job: "Network Engineer",
        gender: "male",
        countryCode: "+7 - ",
    },
    {
        firstName: "Helen",
        lastName: "Jones",
        phone: "2112345678",
        email: "helenjones@example.com",
        job: "Content Writer",
        gender: "female",
        countryCode: "+55 - ",
    },
    {
        firstName: "Ivan",
        lastName: "Klein",
        phone: "27111234567",
        email: "ivanklein@example.com",
        job: "SEO Specialist",
        gender: "male",
        countryCode: "+27 - ",
    },
    {
        firstName: "Julia",
        lastName: "Lopez",
        phone: "5512345678",
        email: "julialopez@example.com",
        job: "Graphic Designer",
        gender: "female",
        countryCode: "+52 - ",
    },
    {
        firstName: "Kevin",
        lastName: "Martinez",
        phone: "2112345678",
        email: "kevinmartinez@example.com",
        job: "IT Support",
        gender: "male",
        countryCode: "+30 - ",
    },
    {
        firstName: "Laura",
        lastName: "Nelson",
        phone: "211234567",
        email: "lauranelson@example.com",
        job: "Operations Manager",
        gender: "female",
        countryCode: "+47 - ",
    },
    {
        firstName: "Michael",
        lastName: "O'Connor",
        phone: "11234567",
        email: "michaeloconnor@example.com",
        job: "Business Analyst",
        gender: "male",
        countryCode: "+353 - ",
    },
    {
        firstName: "Nina",
        lastName: "Parker",
        phone: "91234567",
        email: "ninaparker@example.com",
        job: "Customer Support",
        gender: "female",
        countryCode: "+64 - ",
    },
    {
        firstName: "Oscar",
        lastName: "Quinn",
        phone: "21234567",
        email: "oscarquinn@example.com",
        job: "Systems Administrator",
        gender: "male",
        countryCode: "+20 - ",
    },
    {
        firstName: "Paula",
        lastName: "Rodriguez",
        phone: "917654321",
        email: "paularodriguez@example.com",
        job: "Project Manager",
        gender: "female",
        countryCode: "+34 - ",
    },
    {
        firstName: "Quincy",
        lastName: "Scott",
        phone: "2812345678",
        email: "quincyscott@example.com",
        job: "Database Administrator",
        gender: "male",
        countryCode: "+84 - ",
    },
];
